@include('Mainview')
<?php use Illuminate\Support\Facades\Auth; ?>
        <!DOCTYPE html>
<html lang="en">
<head>
    <title>Todo List</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<style>
    .loader {
        border: 16px solid #f3f3f3;
        border-radius: 50%;
        border-top: 16px solid blue;
        border-right: 16px solid green;
        border-bottom: 16px solid red;
        border-left: 16px solid pink;
        width: 120px;
        height: 120px;
        position: absolute;
        top: 50%;
        left: 42%;
        display: none;
        -webkit-animation: spin 2s linear infinite;
        animation: spin 2s linear infinite;
    }

    @-webkit-keyframes spin {
        0% {
            -webkit-transform: rotate(0deg);
        }
        100% {
            -webkit-transform: rotate(360deg);
        }
    }

    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }
</style>
<body>

<div class="container" id="container">
    <div class="row">
        <div class="col-sm-10">

            @yield('navbar')
            {{--  @foreach($result as $resultshowing)
                  <p> the result is {{  $resultshowing->Blogtext}} </p>
              @endforeach--}}
            @foreach($result as $task)
                <li class="list-group-item">
                    BLOG created : <br>{{ $task->Blogtext}}
                    <a class="btn btn-primary btn-xs" data-toggle="modal" name="action" value="openit"
                       href='/blog/{{$task->id}}/{{$task->userwhocreated}}'> Open it-> </a>
                </li>
                Generated by {{$task->userwhocreated}}
                <?php $variable = $task->id;
                $userwhocreated = $task->userwhocreated; ?>
                <br/>
                <br/>
            @endforeach
        </div>
        <div class="col-sm-2">
            @foreach($listofusers as $task)
                <div class="well">
                    <a> {{$task->name}}</a>
                    <a href='/user/{{$task->email}}'><br>O</a>
                </div>
            @endforeach
        </div>

        <div class="loader"></div>
        <div class="container">

            <div class="row">
                <div class="col-sm-10">
                    @if(strcmp($commentstatus,'empty'))
                        <h2 align="center">Comments</h2>
                        <br/><br/>
                        <ul class="list-group">
                            <form>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="comment"
                                           placeholder="Comments please" name="commentdata" required>
                                </div>

                                <button id="submitbutton" type="button" class="btn btn-default" name="Blogid" value="{{$variable}}"
                                        onclick="return postTheComment()">Submit
                                </button>
                            </form>
                            <br/><br/>
                            @yield('content')
                        </ul>

                        <ul id="commentid">
                            <input id="input-cmnt" style="display: none;">
                        @foreach($comments as $task)
                                <li class="list-group-item" id="{{$task->commentid}}">
                                    {{$task->Commentdoneby}} says: <br>
                                    <p id="{{$task->commentid}}1">{{$task->Comment}}</p>
                                    @if((!strcmp($userwhocreated,\Illuminate\Support\Facades\Auth::user()->email)||!strcmp($task->Commentdoneby,\Illuminate\Support\Facades\Auth::user()->email)))

                                        <span><button class="btn btn-primary btn-xs" type="button"
                                                                    onclick="return deleteTheComment({{$task->commentid}})">X</button></span>
                                    @endif
                                    @if(!strcmp($task->Commentdoneby,\Illuminate\Support\Facades\Auth::user()->email))
                                        <span><button class="btn btn-primary btn-xs" type="button"
                                                                    onclick=" return updateTheComment({{$task->commentid}})">Update</button></span>
                                    @endif
                                </li>

                            @endforeach
                        </ul>

                    @else
                        <div class="row">
                            <div class="col-sm-10">
                                <h4>Be the first one to comment for the blog</h4>
                            </div>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
<script>

    function deleteTheComment($commentid) {
        var _token = $('input[name="_token"]').val();
        $.ajax({
            type: 'POST',
            url: "{{ route('deletecomment') }}",
            data: {
                _token: _token,
                commentid: $commentid,
            },
            success: function (data) {
                $('#'+$commentid).slideUp();


            },
            error: function (data) {
                alert("error");
            }

        });
    }

    /*function oncick() {
        if(){
            updateTheComment()
        }
        else{
            postTheComment();
        }
    }*/
   function updateTheComment(commentid) {

        $('#submitbutton').attr("onclick","updateTheComment("+commentid+")");

        var _token = $('input[name="_token"]').val();
        var commentdata = $('input[name="commentdata"]').val();

        var data = $('#'+commentid+'1').text();
        $('#comment').val(data);

        $('#comment').attr('placeholder','enter the updated data');
        $('#submitbutton').html('update submit');
        /*
       $('#submitbutton').onclick(function () {
           alert("now the ajax request will be processed");*/
        if (commentdata != '') {
            $('.validation').hide();
            $.ajax({
                type: 'POST',
                url: '{{route('updatecomment')}}',
                data: {
                    _token: _token,
                    commentdata: commentdata,
                    commentid: commentid
                },
                success: function (data) {
                    $('#comment').val('');
                    $('#submitbutton').html('submit');
                    $('#submitbutton').attr("onclick","postTheComment()");
                    $('#'+commentid+'1').text(commentdata);
                },
                error: function (data) {
                alert("error");
                }

            })
        }else{
            $('#comment').parent().after("<div class='validation' style='display: block'>Please fill this field</div>");
        }

    }



    function postTheComment() {
            if ($('input[name="commentdata"]').val() != '') {

              $('.validation').hide();

                        {{--values are being saved from php to jquery variables , so that the computation becomes easy --}}

                var _token = $('input[name="_token"]').val();
                var commentdata = $('input[name="commentdata"]').val();
                var Blogid = '{{ $variable}}';
                var userwhocreated = '{{$userwhocreated}}';
                var user = '{{\Illuminate\Support\Facades\Auth::user()->email}}';

                $(document).ajaxStart(function () {
                    $('.loader').show();
                }).ajaxStop(function () {
                    $('.loader').hide();
                });

                $.ajax({
                    type: 'POST',
                    url: " {{ route('addcomment') }}",
                    data: {
                        _token: _token,
                        commentdata: commentdata,
                        Blogid: Blogid
                    },
                    {{--as here what is being done is that,if the value proved to be true from the server and then the following data could be proved success response--}}
                            {{--we are adding the list items dynamically where the values are being checked, THat whether the User has the permission to Update or delete the comment or not--}}
                    success: function (data) {


                        $('#comment').val('');

                        var Blogtext = '<li class="list-group-item" id='+data.commentid+'>' + data.commentDoneBy + " says as:" + '<br/>' + '<p id='+data.commentid+'1>'+data.commentDataFromController+'</p>' +

                            '<span><button class="btn btn-primary btn-xs" type="button" onclick=" return deleteTheComment('+data.commentid+')">X</button></span>';


                        var Buttontext = '<span><button class="btn btn-primary btn-xs" type="button" onclick=" return updateTheComment('+data.commentid+')">Update</button></span>';

/*
                        usage of TERNARY OPERATOR , Since If-else usage was generating variant outcomes...TWO ternary operators are used to check nested hierarchy,due to the logic
*/

$('#commentid').append(!(userwhocreated.localeCompare(user)) || !(data.commentDoneBy.localeCompare(user)) ? (!(data.commentDoneBy.localeCompare(user)) ? Blogtext + Buttontext : (Blogtext)) : Blogtext + '</li>');


                    },
                    error: function (data) {
                        alert("error while pushing ");
                    }
                });

            } else {
                $('#comment').parent().after("<div class='validation' style='display: block'>Please fill this field</div>");
            }
            return false;
        }
</script>
</body>
</html>
