@include('Mainview')
        <!DOCTYPE html>
<html lang="en">
<head>
    <title>Todo List</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-sm-10">

            @yield('navbar')
            {{--  @foreach($result as $resultshowing)
                  <p> the result is {{  $resultshowing->Blogtext}} </p>
              @endforeach--}}


            @foreach($result as $task)
                <li class="list-group-item">
                    BLOG created : <br>{{ $task->Blogtext}}
                    <a class="btn btn-primary btn-xs" data-toggle="modal" name="action" value="openit" href='/blog/{{$task->id}}/{{$task->userwhocreated}}'> Open it-> </a>
                </li>
                Generated by {{$task->userwhocreated}}
           <?php $variable = $task->id?>
                <br/>
                <br/>
            @endforeach
        </div>
        <div class="col-sm-2">
            @foreach($listofusers as $task)
                <div class="well">
                    <a> {{$task->name}}</a>
                    <a href='/user/{{$task->email}}'><br>O</a>
                </div>
            @endforeach
        </div>

        <div class="container">

            <div class="row">
                <div class="col-sm-10">
         @if(strcmp($commentstatus,'empty'))
                        <h2 align="center">Comments</h2>
                        <br/><br/>
                        <ul class="list-group">
                            <form method="get" action="\addcomment">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="todo" name="commentdata"
                                           placeholder="Comments please" required>
                                </div>

                                <button type="submit" class="btn btn-default" name="Blogid" value="{{$variable}}">Submit</button>
                            </form>
                            <br/><br/>
                            @yield('content')
                        </ul>

                    @foreach($comments as $task)
                            <li class="list-group-item">
                                {{$task->Commentdoneby}} says: <br>{{$task->Comment}}
                            </li>

                        @endforeach
              @else
                        <div class="row">
                            <div class="col-sm-10">
                                <h4>Be the first one to comment for the blog</h4>
                            </div>
                </div>
             @endif
    </div>
</div>
</div>
</body>
</html>
