@include('Mainview')
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Todo List</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
@yield('navbar')
  {{--  @foreach($result as $resultshowing)
        <p> the result is {{  $resultshowing->Blogtext}} </p>
    @endforeach--}}

    <div class="container">
        <div class="row">
            <div class="col-sm-10">
                <ul class="list-group">
                    @foreach ($result as $task)

                    <li class="list-group-item">
                        BLOG created : <br>{{ $task->Blogtext }}
                        <a class="btn btn-primary btn-xs" data-toggle="modal" name="action" value="openit" href='/blog/{{$task->id}}/{{$task->userwhocreated}}'> Open it-> </a>
                    </li>
                    Generated by {{$task->userwhocreated}}
                    @endforeach

                </ul>
            </div>
            <div class="col-sm-2">
               @foreach($listofusers as $task)
                    <div class="well">
                        <a> {{$task->name}}</a>
                        <a href='/user/{{$task->email}}'><br>O</a>
                    </div>
                   @endforeach
            </div>
        </div>
    </div>
</div>

</body>
</html>
